// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package persistence

import ()

type Route struct {
	ID        int64
	Path      string
	ServiceID int64
}

type Service struct {
	ID      int64
	Backend string
}
